name: Deploy Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  PROJECT_ID: exemplary-proxy-469221-n8
  REGION: asia-southeast2
  AR_REPO: ml-apps
  SERVICE: churn-api
  PORT: "8000"
  WORKLOAD_IDENTITY_PROVIDER: projects/587466025917/locations/global/workloadIdentityPools/github/providers/github-oidc
  SERVICE_ACCOUNT: gh-actions-deployer@exemplary-proxy-469221-n8.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev -q

      - name: Build & Push
        run: |
          IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.SERVICE }}:${{ github.sha }}
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV
          docker build -t "${IMAGE_URI}" .
          docker push "${IMAGE_URI}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image "${IMAGE_URI}" \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port ${{ env.PORT }}
